# Generated by Django 3.1.6 on 2021-04-02 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('firstname', models.CharField(db_column='Firstname', max_length=30)),
                ('lastname', models.CharField(db_column='Lastname', max_length=30)),
                ('email', models.CharField(db_column='Email', max_length=50, unique=True)),
                ('contact', models.IntegerField(unique=True)),
            ],
            options={
                'db_table': 'agent',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('firstname', models.CharField(db_column='Firstname', max_length=30)),
                ('lastname', models.CharField(db_column='Lastname', max_length=30)),
                ('email', models.CharField(db_column='Email', max_length=50, unique=True)),
                ('contact', models.IntegerField(unique=True)),
            ],
            options={
                'db_table': 'buyer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'login',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OffLogin',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'off_login',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('firstname', models.CharField(db_column='Firstname', max_length=30)),
                ('lastname', models.CharField(db_column='Lastname', max_length=30)),
                ('email', models.CharField(db_column='Email', max_length=50, unique=True)),
                ('contact', models.IntegerField(unique=True)),
            ],
            options={
                'db_table': 'owner',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('l_date', models.DateField(db_column='L_date')),
                ('adress', models.CharField(max_length=255)),
                ('bhk', models.IntegerField()),
                ('p_size', models.IntegerField(db_column='P_size')),
                ('p_status', models.CharField(db_column='P_status', max_length=1)),
                ('p_type', models.CharField(db_column='P_type', max_length=1)),
                ('p_tag', models.CharField(db_column='P_tag', max_length=1)),
                ('p_sug_price', models.IntegerField(db_column='P_sug_price')),
                ('bathrooms', models.IntegerField()),
                ('p_desc', models.TextField(blank=True, db_column='P_desc', null=True)),
            ],
            options={
                'db_table': 'property',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TranRent',
            fields=[
                ('tr_id', models.AutoField(db_column='TR_ID', primary_key=True, serialize=False)),
                ('rent', models.IntegerField()),
                ('st_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'db_table': 'tran_rent',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TranSale',
            fields=[
                ('ts_id', models.AutoField(db_column='TS_ID', primary_key=True, serialize=False)),
                ('sell_price', models.IntegerField()),
                ('s_date', models.DateField()),
            ],
            options={
                'db_table': 'tran_sale',
                'managed': False,
            },
        ),
    ]
